# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20161118_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='photo',
        ),
    ]
