# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20161124_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpView',
            fields=[
                ('signup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='music.SignUp')),
            ],
            bases=('music.signup',),
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_favorite',
            new_name='is_full',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_title',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
