# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20161127_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
    ]
