# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AddField(
            model_name='hi',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hi',
            name='station',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
