# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0011_auto_20161206_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
