# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20161206_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Location'),
        ),
        migrations.AlterField(
            model_name='song',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Location'),
        ),
    ]
