# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20161206_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='song',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
