# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20161206_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hi',
            name='location',
        ),
        migrations.DeleteModel(
            name='Hi',
        ),
    ]
